import { AppSidebar } from '@/components/app-sidebar'
import { SidebarProvider } from '@/components/sidebar-provider'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={process.env.NEXT_PUBLIC_SUPRESS_HYDRATION_WARNING === 'true'}
      >
        <SidebarProvider>
          <div className="flex bg-neutral-50 h-screen">
            <AppSidebar />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
